name: Deploy Sudoku to Bluehost
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key and Known Hosts
        run: |
          echo "${{ secrets.BLUEHOST_SSH_KEY }}" > key
          chmod 600 key
          mkdir -p ~/.ssh
          echo "ezf.jsl.mybluehost.me ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILym/yVa3ddENwpcvknWOcIwJ/0AbKVlHb7a4aD1CVoz" > ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts  # Debug
      - name: Test SSH Connection
        run: |
          ssh -i key -o IdentitiesOnly=yes -o KexAlgorithms=diffie-hellman-group-exchange-sha256 -o UserKnownHostsFile=~/.ssh/known_hosts -v ezfjslmy@${{ secrets.BLUEHOST_HOST }} "whoami"
      - name: Deploy via SSH
        run: |
          ssh -i key -o IdentitiesOnly=yes -o KexAlgorithms=diffie-hellman-group-exchange-sha256 -o UserKnownHostsFile=~/.ssh/known_hosts ezfjslmy@${{ secrets.BLUEHOST_HOST }} "cd ~/public_html/website_4a620043/wp-content/themes/sudoku && git pull origin main"
      - name: Clean Up
        if: always()
        run: |
          rm -f key
