name: Deploy Sudoku to Bluehost
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        run: |
          echo "${{ secrets.BLUEHOST_SSH_KEY }}" > key
          chmod 600 key
      - name: Deploy via SSH
        run: |
          ssh -i key -o IdentitiesOnly=yes -o KexAlgorithms=diffie-hellman-group-exchange-sha256 ezfjslmy@${{ secrets.BLUEHOST_HOST }} "cd ~/public_html/website_4a620043/wp-content/themes/sudoku && git pull origin main"
      - name: Clean Up
        if: always()
        run: |
          rm -f key
