name: Deploy Sudoku to Bluehost
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.8.1
        with:
          host: ${{ secrets.BLUEHOST_HOST }}
          username: ${{ secrets.BLUEHOST_USERNAME }}
          key: ${{ secrets.BLUEHOST_SSH_KEY }}
          key_exchange: "diffie-hellman-group-exchange-sha256"
          script: |
            cd ~/public_html/website_4a620043/wp-content/themes/sudoku
            git pull origin main
