name: Deploy Sudoku to Bluehost
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key and Known Hosts
        run: |
          echo "${{ secrets.BLUEHOST_SSH_KEY }}" > key
          chmod 600 key
          mkdir -p ~/.ssh
          echo "ezf.jsl.mybluehost.me ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILym/yVa3ddENwpcvknWOcIwJ/0AbKVlHb7a4aD1CVoz" > ~/.ssh/known_hosts
      - name: Deploy via SSH
<<<<<<< HEAD
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BLUEHOST_HOST }}
          username: ${{ secrets.BLUEHOST_USERNAME }}
          key: ${{ secrets.BLUEHOST_SSH_KEY }}
          script: |
            cd ~/public_html/website_4a620043/wp-content/themes/sudoku
            git pull origin main
=======
        run: |
          ssh -i key -o IdentitiesOnly=yes -o KexAlgorithms=diffie-hellman-group-exchange-sha256 -o UserKnownHostsFile=~/.ssh/known_hosts -o StrictHostKeyChecking=accept-new ezfjslmy@${{ secrets.BLUEHOST_HOST }} "cd ~/public_html/website_4a620043/wp-content/themes/sudoku && git pull origin main"
      - name: Clean Up
        if: always()
        run: |
          rm -f key
>>>>>>> f8d3d443dfd72e0f81fbc57e41ba1c209d120a7a
